// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TermProject.Models;

namespace TermProject.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20221206222130_Weakness")]
    partial class Weakness
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TermProject.Models.Pokemon", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Attack")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Defense")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Hp")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("PokedexNumber")
                        .IsRequired()
                        .HasColumnName("Pokedex Number")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonType1Id")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonType2Id")
                        .HasColumnType("int");

                    b.Property<int?>("SpAttack")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SpDefense")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Speed")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("PokemonId");

                    b.HasIndex("PokemonType1Id");

                    b.HasIndex("PokemonType2Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            PokemonId = 1,
                            Attack = 49,
                            DateAdded = new DateTime(2022, 12, 6, 17, 21, 29, 919, DateTimeKind.Local).AddTicks(7718),
                            Defense = 49,
                            Hp = 45,
                            Name = "Bulbasaur",
                            PokedexNumber = 1,
                            PokemonType1Id = 12,
                            PokemonType2Id = 4,
                            SpAttack = 65,
                            SpDefense = 65,
                            Speed = 45
                        },
                        new
                        {
                            PokemonId = 2,
                            Attack = 62,
                            DateAdded = new DateTime(2022, 12, 6, 17, 21, 29, 924, DateTimeKind.Local).AddTicks(4627),
                            Defense = 63,
                            Hp = 60,
                            Name = "Ivysaur",
                            PokedexNumber = 2,
                            PokemonType1Id = 12,
                            PokemonType2Id = 4,
                            SpAttack = 80,
                            SpDefense = 80,
                            Speed = 60
                        },
                        new
                        {
                            PokemonId = 3,
                            Attack = 100,
                            DateAdded = new DateTime(2022, 12, 6, 17, 21, 29, 924, DateTimeKind.Local).AddTicks(4801),
                            Defense = 123,
                            Hp = 80,
                            Name = "Venusaur",
                            PokedexNumber = 3,
                            PokemonType1Id = 12,
                            PokemonType2Id = 4,
                            SpAttack = 122,
                            SpDefense = 120,
                            Speed = 80
                        });
                });

            modelBuilder.Entity("TermProject.Models.PokemonType", b =>
                {
                    b.Property<int>("PokemonTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("PokemonTypeId");

                    b.ToTable("PokemonTypes");

                    b.HasData(
                        new
                        {
                            PokemonTypeId = 1,
                            Name = "Normal"
                        },
                        new
                        {
                            PokemonTypeId = 2,
                            Name = "Fighting"
                        },
                        new
                        {
                            PokemonTypeId = 3,
                            Name = "Flying"
                        },
                        new
                        {
                            PokemonTypeId = 4,
                            Name = "Poison"
                        },
                        new
                        {
                            PokemonTypeId = 5,
                            Name = "Ground"
                        },
                        new
                        {
                            PokemonTypeId = 6,
                            Name = "Rock"
                        },
                        new
                        {
                            PokemonTypeId = 7,
                            Name = "Bug"
                        },
                        new
                        {
                            PokemonTypeId = 8,
                            Name = "Ghost"
                        },
                        new
                        {
                            PokemonTypeId = 9,
                            Name = "Steel"
                        },
                        new
                        {
                            PokemonTypeId = 10,
                            Name = "Fire"
                        },
                        new
                        {
                            PokemonTypeId = 11,
                            Name = "Water"
                        },
                        new
                        {
                            PokemonTypeId = 12,
                            Name = "Grass"
                        },
                        new
                        {
                            PokemonTypeId = 13,
                            Name = "Electric"
                        },
                        new
                        {
                            PokemonTypeId = 14,
                            Name = "Psychic"
                        },
                        new
                        {
                            PokemonTypeId = 15,
                            Name = "Ice"
                        },
                        new
                        {
                            PokemonTypeId = 16,
                            Name = "Dragon"
                        },
                        new
                        {
                            PokemonTypeId = 17,
                            Name = "Dark"
                        },
                        new
                        {
                            PokemonTypeId = 18,
                            Name = "Fairy"
                        });
                });

            modelBuilder.Entity("TermProject.Models.TypeWeakness", b =>
                {
                    b.Property<int>("TypeWeaknessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PokemonTypeId")
                        .HasColumnType("int");

                    b.Property<int>("WeaknessId")
                        .HasColumnType("int");

                    b.HasKey("TypeWeaknessId");

                    b.HasIndex("PokemonTypeId");

                    b.HasIndex("WeaknessId");

                    b.ToTable("TypeWeakness");

                    b.HasData(
                        new
                        {
                            TypeWeaknessId = 1,
                            PokemonTypeId = 12,
                            WeaknessId = 10
                        });
                });

            modelBuilder.Entity("TermProject.Models.Pokemon", b =>
                {
                    b.HasOne("TermProject.Models.PokemonType", "PokemonType1")
                        .WithMany()
                        .HasForeignKey("PokemonType1Id");

                    b.HasOne("TermProject.Models.PokemonType", "PokemonType2")
                        .WithMany()
                        .HasForeignKey("PokemonType2Id");
                });

            modelBuilder.Entity("TermProject.Models.TypeWeakness", b =>
                {
                    b.HasOne("TermProject.Models.PokemonType", "PokemonType")
                        .WithMany("TypeWeakness")
                        .HasForeignKey("PokemonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TermProject.Models.PokemonType", "Weakness")
                        .WithMany("Weaknesses")
                        .HasForeignKey("WeaknessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
